### ISSUE TITLE
Add PARiKSHA logo on browser tab

### ISSUE THREAD

**Issue by pulkitvyas08** [CSI-Research-Community/PARiKSHA#15]
The transparent with black outline logo can be found in the assets/images folder. Let me know if the white or coloured one will look better and I'll them too

**Comment by aikanshboyal** [comment]
I want to work on this issue !

**Comment by sannidhya-kushwaha** [comment]
Hey!! assign this work to me. Let me know... you wanna add that logo beside the title on the browser?

**Comment by pulkitvyas08** [comment]
> Let me know... you wanna add that logo beside the title on the browser?
Yes exactly!

**Comment by sannidhya-kushwaha** [comment]
Ya ofcourse!!

**Comment by sannidhya-kushwaha** [comment]
It's done bro!! Merge my pull request...
