### ISSUE TITLE
Fix typo on student's home page

### ISSUE THREAD

**Issue by pulkitvyas08** [CSI-Research-Community/PARiKSHA#20]
The "Attempt Quiz" card on student's homepage has a button that has the text "Attemp Quiz" instead of "Attempt Quiz"

**Comment by aditya28sarin** [comment]
Can you assign me on this issue?

**Comment by pulkitvyas08** [comment]
Sure!

**Comment by aditya28sarin** [comment]
I have corrected the typo and opened a pull request.

**Comment by pulkitvyas08** [comment]
Fixed in #22
