### ISSUE TITLE
Beautify the code

### ISSUE THREAD

**Issue by pulkitvyas08** [CSI-Research-Community/PARiKSHA#24]
In almost every file there are indentation and spacing problems

**Comment by sannidhya-kushwaha** [comment]
Ya I'll try to fix it 👍

**Comment by pulkitvyas08** [comment]
I guess you already have done a lot regarding this issue but sure I'll make assign this one to you as well!

**Comment by sannidhya-kushwaha** [comment]
It's done!! Hope you will like it.

**Comment by pulkitvyas08** [comment]
Looks good! PR #25 is merged now!
